version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-kube
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: testdb
    volumes:
      - mongodb-data:/data/db
      - mongodb-backup:/backup
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  delete-service:
    image: sebastianarce/delete-golang
    container_name: delete-golang-kube
    ports:
      - "8081:8080"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DATABASE: testdb
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongodb-data:
  mongodb-backup:

networks:
  app-network:
